---
apiVersion: v1
kind: Pod
metadata:
  name: console
spec:
  nodeSelector:
    beta.kubernetes.io/arch: amd64
  restartPolicy: Always
  containers:
    - name: console
      image: prlx/k8s-redis-ha:console-3.0.1
